### ISSUE TITLE
New Map: The Frostlands

### ISSUE THREAD

**Issue by seiyria** [LandOfTheRair/landoftherair#825]
Explore the Kingdom of Risan in all of its frozen glory.

The new cap will be 35/27.

Most things are TBD here.

New monsters:
- [x] moose (good chance of cstun - stunning fist boost)
- [x] yeti (good fur) / big yeti (better fur) / clubs (palette swap to ice, frost damage #844)
- [x] sabretooth (frostfang: boss form) tans for cat robe
- [x] winter wolves (bite for ice)
- [x] ice-based snakes, etc (need natural AC, evasion)
- [x] sanquin - cast ice, tan for ice scales
- [x] ice based water creatures (the lobsters with halberds - thermidors - frost damage #844) - should spawn more commonly with plain store hally
- [x] new golems (maybe make some blue ones?) with high AC + punch for ice (#844)
- [x] should also be guards in the guard towers
- [x] townees walking around the town on a route or two
- [x] slaves (minytes) in the castle, walking around town
- [x] repurpose a yeti cave to be brigands (with normal spells, probably give them random names - items should all be frost damage #844 and rare chance of chakram)

Bring in some old monsters:
- [x] wildlife should be imported from the mines

New quests:
- [x] guard kejar, daily quests, give food reward(?) - kill brigands, cats, yetis
- [x] botanist, frozen flower drop + earring?
- [x] gloves: bring frostfang robe + frozen yeti club to king
- [x] ring upgrade: create w/ crafting, upgrade at queen - first is frost larimar, then req ether larimar (copy old ring stats into new ring)

New gear:
- [x] frostflower (light blue spiky gourd)
- [x] ice-based (similar to mines)
- [x] casts dispel on hit
- [x] new earring (+1-3 trait/+y secondary stat - +1? +2?)
- [x] new rings (+X primary/+y secondary) (keep rings - outline pre-craft, single ring basic, double ring upgraded, gigantic ring later)
- [x] new boots
- [x] new gloves/claws
- [x] frost circle (offhand, throwing dagger, bonus ice damage) (should do frost damage #844)
- [x] poison/disease gems (25 instead of 50)
- [x] new level 21 gems (more ac, mitigation, damage reduction, abs)
- [x] new, stronger thief traps
- [x] yeti bile food
- [x] frost shield (medusa palette swap)
- [x] new store basic gear
- [x] new weapons at tier 6

Populated resources:

- [x] ore
- [x] flowers
- [x] trees

Regions:
- [x] succor
- [x] descriptions

Town shops:
- [x] vendors

New crafts:
- [x] the basic machleum ring (owts+owts = ring) - can be sold - has no properties, but it used in crafts
